# Minimal skia stub for mypy
from typing import Any

# permissive attribute importer
def __getattr__(name: str) -> Any: ...

# Minimal placeholder types commonly referenced by the codebase
class Paint:
    def __init__(self) -> None: ...
    def setAntiAlias(self, enabled: bool) -> None: ...
    def setColor(self, color: int) -> None: ...

class Rect:
    @staticmethod
    def MakeXYWH(x: int, y: int, w: int, h: int) -> "Rect": ...

class RRect:
    @staticmethod
    def MakeRectXY(r: "Rect", rx: float, ry: float) -> "RRect": ...

class Surface: ...
class Color: ...

def ColorSetARGB(a: int, r: int, g: int, b: int) -> int: ...
